base_score: null
booster: null
callbacks: null
colsample_bylevel: null
colsample_bynode: null
colsample_bytree: 0
early_stopping_rounds: null
enable_categorical: false
eval_metric: null
feature_types: null
features: '[''age'', ''sex'', ''bmi'', ''children'', ''smoker'', ''region'']'
gamma: 3.828700144119227
gpu_id: null
grow_policy: null
importance_type: null
interaction_constraints: null
learning_rate: null
max_bin: null
max_cat_threshold: null
max_cat_to_onehot: null
max_delta_step: null
max_depth: 3
max_leaves: null
min_child_weight: 9
missing: .nan
model_class: XGBRegressor
monotone_constraints: null
n_estimators: 200
n_jobs: null
num_parallel_tree: null
objective: reg:squarederror
predictor: null
random_state: null
reg_alpha: 100
reg_lambda: null
sampling_method: null
scale_pos_weight: null
subsample: null
tree_method: null
use_label_encoder: false
validate_parameters: null
verbosity: null
