defaults:
  - process: process
  - model: model
  - _self_

raw:
  path: data/raw/insurance.csv

processed:
  dir: data/processed
  X_train:
    name: X_train.csv
    path: ${processed.dir}/${processed.X_train.name}
  X_test:
    name: X_test.csv
    path: ${processed.dir}/${processed.X_test.name}
  y_train:
    name: y_train.csv
    path: ${processed.dir}/${processed.y_train.name}
  y_test:
    name: y_test.csv
    path: ${processed.dir}/${processed.y_test.name}

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

model:
  dir: models
  name: xgboost
  path: ${model.dir}/${model.name}

mlflow_tracking_ui:
  file:\Mi unidad\01_Oriol\00_Proyectos\202306_mlops_medical_cost\mlruns\
mlflow_USERNAME: omarcosan
mlflow_PASSWORD: 1234
